apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-workflow1
  labels:
    app: test-workflow1
  namespace: namespace-workflow-1677857582182
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-workflow1
  template:
    metadata:
      labels:
        app: test-workflow1
    spec:
      containers:
        - name: test-workflow1
          image: acrworkflow1677857582182.azurecr.io/image-workflow-1677857582182:latest
          ports:
            - containerPort: 8080