apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-test-workflow
  labels:
    app: my-test-workflow
    kubernetes.azure.com/generator: devhub
  namespace: namespace-workflow-1719508233844
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-test-workflow
  template:
    metadata:
      labels:
        app: my-test-workflow
    spec:
      containers:
        - name: my-test-workflow
          image: acrworkflow1719508233844.azurecr.io/image-workflow-1719508233844:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
