apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-go-workflow
  labels:
    app: test-go-workflow
    kubernetes.azure.com/generator: devhub
  namespace: go-echo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-go-workflow
  template:
    metadata:
      labels:
        app: test-go-workflow
    spec:
      containers:
        - name: test-go-workflow
          image: brfoletestacr.azurecr.io/image-workflow-1730326970010:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80