apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-workflow-1
  labels:
    app: test-workflow-1
  namespace: namespace-workflow-1713207862407
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-workflow-1
  template:
    metadata:
      labels:
        app: test-workflow-1
    spec:
      containers:
        - name: test-workflow-1
          image: acrworkflow1713207862407.azurecr.io/image-workflow-1713207862407:latest
          ports:
            - containerPort: 80