apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-eastus2
  labels:
    app: test-eastus2
    kubernetes.azure.com/generator: devhub
  namespace: namespace-workflow-1723219377230
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-eastus2
  template:
    metadata:
      labels:
        app: test-eastus2
    spec:
      containers:
        - name: test-eastus2
          image: acrworkflow1723219377230.azurecr.io/image-workflow-1723219377230:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
