apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-westus2
  labels:
    app: test-westus2
    kubernetes.azure.com/generator: devhub
  namespace: namespace-workflow-1723219484505
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-westus2
  template:
    metadata:
      labels:
        app: test-westus2
    spec:
      containers:
        - name: test-westus2
          image: acrworkflow1723219484505.azurecr.io/image-workflow-1723219484505:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
