apiVersion: apps/v1
kind: Deployment
metadata:
  name: test123
  labels:
    app: test123
  namespace: namespace-workflow-1697551895021
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test123
  template:
    metadata:
      labels:
        app: test123
    spec:
      containers:
        - name: test123
          image: acrworkflow1697551895021.azurecr.io/image-workflow-1697551895021:latest
          ports:
            - containerPort: 80