apiVersion: v1
kind: Service
metadata:
  name: testworkflow
  namespace: namespace-workflow-1691526923756
spec:
  type: LoadBalancer
  selector:
    app: testworkflow
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080