apiVersion: v1
kind: Service
metadata:
  name: test123
  namespace: namespace-workflow-1697551895021
spec:
  type: LoadBalancer
  selector:
    app: test123
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80