apiVersion: v1
kind: Service
metadata:
  name: my-test-workflow
  namespace: namespace-workflow-1719508233844
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: my-test-workflow
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80