apiVersion: v1
kind: Service
metadata:
  name: test-eastus2
  namespace: namespace-workflow-1723219377230
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: test-eastus2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80