apiVersion: v1
kind: Service
metadata:
  name: testapp
  namespace: testnamespace
spec:
  type: LoadBalancer
  selector:
    app: testapp
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080